spring.application.name=sms_singup_login_api
server.port=9090

#		MySQL properties
spring.datasource.url=${mysql_url}
spring.datasource.username=${mysql_username}
spring.datasource.password=${mysql_password}
spring.datasource.url=jdbc:mysql://localhost:3306/apj
spring.datasource.username=root
spring.datasource.password=198812Apjs$$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

#spring.datasource.password=M10muth
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.id.new_generator_mappings=false

#spring.jpa.properties.hibernate.format_sql=true

